### ISSUE TITLE
ffmpeg -vol arg Mp3 milliseconds double 

### ISSUE THREAD

**Issue by ShisanXing** [quippy-git/javamod#1]
I use v2.3 (java) build my mp3 player, if use ffmpeg -vol mp3file, I always get double milliseconds, the frame_size is difference with original file, what should I do ?

**Comment by quippy-git** [comment]
You should provide a bitrate like this:
ffmpeg -i <INPUT.FILE> -vol 256 -b:a 128k <OUTPUT.mp3>
Files generated that way will work with JavaMod

However, if files are generated this way:
ffmpeg -i <INPUT.FILE> -vol 256 <OUTPUT.mp3> 
without a bitrate provided, ffmpg will set a bitrate of 64kbs in the header, but the length suggests, that it's 128kbs in reality.

The problem is, that the headers of such generated files (without KBS provided) and those, generated explecitly on 64kbs are identical, so I so far do not know how to destinguish these two files.

**Comment by quippy-git** [comment]
Stepping deeper into this I found out I did not read Info-Header (same as Xing header, but for CBR). I parse that now and it works.

**Comment by ShisanXing** [comment]
thanks.
