### ISSUE TITLE
LTS support

### ISSUE THREAD

**Issue by JoopN** [quippy-git/javamod#2]
IMPORTANT: as JDK 8 LTS support will be over in two years (security) and normal support is already over, JavaMod is now using JDK 17 (LTS). As the compile level changed, you must use JDK 17 to run JavaMod!

I don't know where you got this info, I have this from Bellsoft;
![support roadmap java](https://user-images.githubusercontent.com/8764153/177303468-05abad6b-e529-4997-a2fe-0e29942646a7.jpg)

According to this information your JDK 17 has an end of support which is BEFORE end of support of JDK 8.

**Comment by quippy-git** [comment]
I got my infos from here:
https://endoflife.date/java
That is the Lifetime of openJDK. 

It might be that Oracle or other implementors of Java might provide different lifetime for their implementations because of licensing or paying customers.

And further more I wanted to be able to use new features of newer JDK and adopt/get rid of possible deprecated methods.

Using a more modern JDK is not an issue.

And just as an addition to this: you are not encouraged to use Javamod with JDK8 - even though its compile level was JDK8. In the V3.2 readme I already stated:
_However: run with modern Java (openJDK >11, 64BIT) to gain full speed - 200+ NNAs are no problem then
**Heap Size with JDK8 (default of 256M) not sufficient with bigger mods.** Either set -Xmx1024m parameter or use newer JDK_ 

That said, I cannot think of anybody using javamod with JDK8 as most Impulsetracker Mods will not work then, so updating to a new LTS-Version is a logical consequence and should not affect anybody.

The reasons to migrate to JDK17 are manifold. The fact that JDK8 is now slowly being phased out is just one of many.
