### ISSUE TITLE
Can't play .XM music.

### ISSUE THREAD

**Issue by ghost** [quippy-git/javamod#4]
When I gonna open my .xm tracker music for example, app just freezing and not responding.
Music source in attachment:
[music.zip](https://github.com/quippy-git/javamod/files/12123644/music.zip)

**Comment by quippy-git** [comment]
Accidentally commented in other issue thread. To complete documentation of the issue, so that is not closed without comment:

The XM is now read correctly. It had instruments without samples and indicated that with 0xFFFF instead of 0 - but I read the amount of samples as "unsigned word" and got 65535 - not -1... Reading so many samples might end in a very long loop, till memory is out.
